---
name: abersoft_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  quiver: ^3.2.1
  shared_preferences: ^2.1.2
  http: ^0.13.6
dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  json_to_model: ^3.2.4
flutter:
  uses-material-design: true
