---
name: abersoft_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  quiver: ^3.2.1
  shared_preferences: ^2.1.2
  http: ^0.13.6
  get_storage: ^2.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_gen: ^5.3.1
  form_validator: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.3.2
  image_picker: ^1.0.0
dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  json_to_model: ^3.2.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
flutter_gen:
  output: lib/gen/
  line_length: 80